<div>
    <x-slot name="header"><x-page-header :title="__t('customer_report', 'reports')" :description="__t('customer_description', 'reports')" /></x-slot>
    <div class="space-y-6">
        <x-card><form wire:submit="applyFilters" class="grid gap-4 md:grid-cols-2 xl:grid-cols-[1fr_1fr_1.4fr_auto] xl:items-start"><div><label for="customers-from" class="mb-1 block text-sm font-medium text-primary-700">{{ __t('date_from', 'reports') }}</label><input id="customers-from" type="date" wire:model="dateFrom" class="w-full rounded-xl border-primary-300 text-sm">@error('dateFrom')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div><div><label for="customers-to" class="mb-1 block text-sm font-medium text-primary-700">{{ __t('date_to', 'reports') }}</label><input id="customers-to" type="date" wire:model="dateTo" class="w-full rounded-xl border-primary-300 text-sm">@error('dateTo')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div><div><label for="customer-search" class="mb-1 block text-sm font-medium text-primary-700">{{ __t('search', 'reports') }}</label><input id="customer-search" type="search" wire:model.live.debounce.300ms="search" placeholder="{{ __t('search_customers', 'reports') }}" class="w-full rounded-xl border-primary-300 text-sm"></div><button type="submit" class="mt-6 h-10 rounded-xl bg-primary-900 px-5 text-sm font-semibold text-white hover:bg-primary-800">{{ __t('apply_filters', 'reports') }}</button></form></x-card>
        <div class="grid gap-4 sm:grid-cols-3"><x-stat-card :label="__t('buying_customers', 'reports')" :value="number_format($summary['customers'])" variant="neutral" /><x-stat-card :label="__t('purchases', 'reports')" :value="number_format($summary['purchases'])" variant="info" /><x-stat-card :label="__t('total_sold', 'reports')" :value="$currency['symbol'].number_format($summary['total'], 2)" :trend="$currency['code']" variant="success" /></div>
        <x-card :title="__t('customer_ranking', 'reports')" :description="__t('customer_ranking_description', 'reports')">
            <div class="mb-4 flex justify-end"><x-per-page-select wire:model.live="perPage" /></div>
            @if ($customers->isEmpty())<x-empty-state :title="__t('no_results', 'reports')" :description="__t('no_customers_period', 'reports')" />@else
                <div class="-mx-5 overflow-x-auto"><table class="min-w-full divide-y divide-primary-200 text-sm"><thead class="bg-primary-50 text-left text-xs font-semibold uppercase text-primary-500"><tr><th class="px-5 py-3">#</th><th class="px-5 py-3">{{ __t('customer', 'reports') }}</th><th class="px-5 py-3">{{ __t('document', 'reports') }}</th><th class="px-5 py-3 text-right">{{ __t('purchases', 'reports') }}</th><th class="px-5 py-3 text-right">{{ __t('purchased_total', 'reports') }}</th></tr></thead><tbody class="divide-y divide-primary-100">@foreach ($customers as $customer)<tr><td class="px-5 py-3 font-semibold text-primary-500">{{ $customers->firstItem() + $loop->index }}</td><td class="px-5 py-3"><p class="font-semibold text-primary-900">{{ $customer->name }}</p><p class="text-xs text-primary-500">{{ $customer->email ?: '—' }}</p></td><td class="px-5 py-3 text-primary-600">{{ $customer->document }}</td><td class="px-5 py-3 text-right"><x-badge variant="info">{{ $customer->purchases_count }}</x-badge></td><td class="px-5 py-3 text-right font-semibold">{{ $currency['symbol'] }}{{ number_format((float) $customer->purchases_total, 2) }}</td></tr>@endforeach</tbody></table></div><div class="mt-4">{{ $customers->links() }}</div>
            @endif
        </x-card>
    </div>
</div>
